name: mytodo_fe app

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm ci

      - name: Build React App
        run:  npm run build
        env:
            CI: false
            REACT_APP_API_URL: ${{ vars.PROD_REACT_APP_API_URL }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.PROD_AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 sync build/ s3://${{ vars.PROD_S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.PROD_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

  